services:
  ccc_ocr:
    image: laulj/ccc_ocr-tensorflow-cuda11.2:1.1.0
    container_name: ccc_paddleocr
    stdin_open: true
    tty: true
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
       - ./dataset:/home/PaddleOCR/dataset
